date = "2024-07-16"
target_stop_ids = [
  "mtc:12th-st-oakland-city-center-bart",
  "mtc:19th-st-oakland-bart",
  "mtc:civic-center-bart",
  "mtc:daly-city-bart",
  "mtc:dublin/-pleasanton-bart",
  "mtc:el-cerrito-del-norte-bart",
  "mtc:embarcadero-bart",
  "mtc:fruitvale",
  "mtc:great-mall/milpitas-bart",
  "mtc:macarthur-bart",
  "mtc:millbrae-bart",
  "mtc:montgomery-bart",
  "mtc:oakland-coliseum-bart",
  "mtc:pleasant-hill-bart",
  "mtc:powell",
  "mtc:richmond-bart/amtrak",
  "mtc:sfo",
  "mtc:union-city-bart",
  "mtc:walnut-creek-bart",
  "mtc:warm-springs-south-fremont-bart",
  "place_16TH",
  "place_24TH",
  "place_ANTC",
  "place_ASHB",
  "place_BALB",
  "place_BAYF",
  "place_BERY",
  "place_CAST",
  "place_COLM",
  "place_CONC",
  "place_DBRK",
  "place_FRMT",
  "place_GLEN",
  "place_HAYW",
  "place_LAFY",
  "place_LAKE",
  "place_NBRK",
  "place_NCON",
  "place_ORIN",
  "place_PCTR",
  "place_PITT",
  "place_PLZA",
  "place_ROCK",
  "place_SANL",
  "place_SBRN",
  "place_SHAY",
  "place_SSAN",
  "place_WDUB",
  "place_WOAK",
]

[[gtfs]]
dir = "data/scratch/fetched-2024-08-03/RG"
prefix = ""
segment_stop_ids = []
