date = "2024-06-10"
target_stop_ids = [
  "64747",
  "64748",
  "64749",
  "64772",
  "64773",
  "64774",
  "65866",
  "PS_ALDR",
  "PS_ALUM",
  "PS_BASC",
  "PS_BAYP",
  "PS_BLSM",
  "PS_BONA",
  "PS_BORR",
  "PS_BRNM",
  "PS_BRRS",
  "PS_CDMS",
  "PS_CHMP",
  "PS_CISC",
  "PS_CIVC",
  "PS_CMBL",
  "PS_COMP",
  "PS_CONV",
  "PS_CPTL",
  "PS_CROP",
  "PS_CRSS",
  "PS_CTTL",
  "PS_CURT",
  "PS_FAIR",
  "PS_FRTD",
  "PS_GISH",
  "PS_GRAM",
  "PS_GRML",
  "PS_HAML",
  "PS_HOST",
  "PS_JAPN",
  "PS_KRNA",
  "PS_LICK",
  "PS_LOCK",
  "PS_METR",
  "PS_MIDD",
  "PS_MKEE",
  "PS_MOFF",
  "PS_NASA",
  "PS_OHLO",
  "PS_OLDI",
  "PS_ORCH",
  "PS_PENC",
  "PS_RACE",
  "PS_REAM",
  "PS_ROAK",
  "PS_SFND",
  "PS_SNLL",
  "PS_TAMN",
  "PS_TASM",
  "PS_TRSA",
  "PS_VIEN",
  "PS_VIRG",
  "PS_WHIS",
  "PS_WINC",
  "mtc:great-mall/milpitas-bart",
  "mtc:mountain-view-station",
  "mtc:san-jose-diridon-station",
]

[[gtfs]]
dir = "data/scratch/fetched-2024-08-03/RG"
prefix = ""
segment_stop_ids = []
