# date = "2024-08-31"
date = "2024-06-07"
target_stop_ids = [
  "bart-OAKL",
  "bart-place_12TH",
  "bart-place_16TH",
  "bart-place_19TH",
  "bart-place_24TH",
  "bart-place_ANTC",
  "bart-place_ASHB",
  "bart-place_BALB",
  "bart-place_BAYF",
  "bart-place_BERY",
  "bart-place_CAST",
  "bart-place_CIVC",
  "bart-place_COLM",
  "bart-place_COLS",
  "bart-place_CONC",
  "bart-place_DALY",
  "bart-place_DBRK",
  "bart-place_DELN",
  "bart-place_DUBL",
  "bart-place_EMBR",
  "bart-place_FRMT",
  "bart-place_FTVL",
  "bart-place_GLEN",
  "bart-place_HAYW",
  "bart-place_LAFY",
  "bart-place_LAKE",
  "bart-place_MCAR",
  "bart-place_MLBR",
  "bart-place_MLPT",
  "bart-place_MONT",
  "bart-place_NBRK",
  "bart-place_NCON",
  "bart-place_ORIN",
  "bart-place_PCTR",
  "bart-place_PHIL",
  "bart-place_PITT",
  "bart-place_PLZA",
  "bart-place_POWL",
  "bart-place_RICH",
  "bart-place_ROCK",
  "bart-place_SANL",
  "bart-place_SBRN",
  "bart-place_SFIA",
  "bart-place_SHAY",
  "bart-place_SSAN",
  "bart-place_UCTY",
  "bart-place_WARM",
  "bart-place_WCRK",
  "bart-place_WDUB",
  "bart-place_WOAK",
]

[[gtfs]]
# dir = "data/scratch/fetched-2024-07-20/bart"
dir = "data/fetched-2024-06-08/bart"
prefix = "bart-"
segment_stop_ids = [
  "bart-OAKL",
  "bart-place_12TH",
  "bart-place_16TH",
  "bart-place_19TH",
  "bart-place_24TH",
  "bart-place_ANTC",
  "bart-place_ASHB",
  "bart-place_BALB",
  "bart-place_BAYF",
  "bart-place_BERY",
  "bart-place_CAST",
  "bart-place_CIVC",
  "bart-place_COLM",
  "bart-place_COLS",
  "bart-place_CONC",
  "bart-place_DALY",
  "bart-place_DBRK",
  "bart-place_DELN",
  "bart-place_DUBL",
  "bart-place_EMBR",
  "bart-place_FRMT",
  "bart-place_FTVL",
  "bart-place_GLEN",
  "bart-place_HAYW",
  "bart-place_LAFY",
  "bart-place_LAKE",
  "bart-place_MCAR",
  "bart-place_MLBR",
  "bart-place_MLPT",
  "bart-place_MONT",
  "bart-place_NBRK",
  "bart-place_NCON",
  "bart-place_ORIN",
  "bart-place_PCTR",
  "bart-place_PHIL",
  "bart-place_PITT",
  "bart-place_PLZA",
  "bart-place_POWL",
  "bart-place_RICH",
  "bart-place_ROCK",
  "bart-place_SANL",
  "bart-place_SBRN",
  "bart-place_SFIA",
  "bart-place_SHAY",
  "bart-place_SSAN",
  "bart-place_UCTY",
  "bart-place_WARM",
  "bart-place_WCRK",
  "bart-place_WDUB",
  "bart-place_WOAK",
]
