date = "2024-06-10"
target_stop_ids = [
  "bart-place_LAKE",
  "bart-place_BERY",
  "bart-place_DUBL",
  "bart-place_BAYF",
  "bart-OAKL",
  "bart-place_COLS",
  "bart-place_ANTC",
  "bart-place_RICH",
  "bart-place_MCAR",
  "bart-place_19TH",
  "bart-place_12TH",
  "bart-place_WOAK",
  "bart-place_BALB",
  "bart-place_MLBR",
]

[[gtfs]]
dir = "data/fetched-2024-06-08/bart"
prefix = "bart-"
segment_stop_ids = [
  "bart-place_LAKE",
  "bart-place_BERY",
  "bart-place_DUBL",
  "bart-place_BAYF",
  "bart-OAKL",
  "bart-place_COLS",
  "bart-place_ANTC",
  "bart-place_RICH",
  "bart-place_MCAR",
  "bart-place_19TH",
  "bart-place_12TH",
  "bart-place_WOAK",
  "bart-place_BALB",
  "bart-place_MLBR",
]
